### PR TITLE
Feature/standings

### PR DESCRIPTION
**Pull request by Abrissirba**
Adding clients for standings and venues

### CODE REVIEW

**Comment by BorisGerretzen** [comment]
First time someone left a pr on one of my repos <3

The merge button said the merge failed but it went through fine, new version 1.0.8 is up on NuGet.

**Comment by Abrissirba** [comment]
Nice, happy to help. Will you publish an updated version of the nuget package aswell?

**Comment by BorisGerretzen** [comment]
Should be up already, sometimes it takes a while for them to scan it before it's visible

**Comment by Abrissirba** [comment]
In case you are interested what I use this library for: https://groundhopfer.com

**Comment by BorisGerretzen** [comment]
Looks good! What frontend framework did you use?

**Comment by Abrissirba** [comment]
It is nextjs with tailwind and material ui.

**Pull request closed without merging**
